var countries = {ru: [
	{ id: 0, name: "Все страны" }, 
	{ id: 375, name: "Абхазия" }, 
	{ id: 1, name: "Австралия" }, 
	{ id: 2, name: "Австрия" }, 
	{ id: 3, name: "Азербайджан" }, 
	{ id: 4, name: "Албания" }, 
	{ id: 5, name: "Алжир" }, 
	{ id: 7, name: "Ангилья" }, 
	{ id: 8, name: "Ангола" }, 
	{ id: 9, name: "Андорра" }, 
	{ id: 10, name: "Антигуа и Барбуда" }, 
	{ id: 11, name: "Аргентина" }, 
	{ id: 12, name: "Армения" }, 
	{ id: 13, name: "Аруба" }, 
	{ id: 14, name: "Афганистан" }, 
	{ id: 15, name: "Багамские острова" }, 
	{ id: 16, name: "Бангладеш" }, 
	{ id: 17, name: "Барбадос" }, 
	{ id: 18, name: "Бахрейн" }, 
	{ id: 19, name: "Беларусь" }, 
	{ id: 20, name: "Белиз" }, 
	{ id: 21, name: "Бельгия" }, 
	{ id: 22, name: "Бенин" }, 
	{ id: 23, name: "Бермудские острова" }, 
	{ id: 24, name: "Болгария" }, 
	{ id: 25, name: "Боливия" }, 
	{ id: 26, name: "Босния и Герцеговина" }, 
	{ id: 27, name: "Ботсвана" }, 
	{ id: 28, name: "Бразилия" }, 
	{ id: 29, name: "Британские Виргинские острова" }, 
	{ id: 30, name: "Бруней" }, 
	{ id: 31, name: "Буркина-Фасо" }, 
	{ id: 32, name: "Бурунди" }, 
	{ id: 33, name: "Бутан" }, 
	{ id: 34, name: "Вануату" }, 
	{ id: 224, name: "Ватикан" }, 
	{ id: 35, name: "Великобритания" }, 
	{ id: 36, name: "Венгрия" }, 
	{ id: 37, name: "Венесуэла" }, 
	{ id: 38, name: "Виргинские острова (США)" }, 
	{ id: 437, name: "Вознесения о-в" }, 
	{ id: 39, name: "Восточный Тимор" }, 
	{ id: 40, name: "Вьетнам" }, 
	{ id: 41, name: "Габон" }, 
	{ id: 42, name: "Гаити" }, 
	{ id: 43, name: "Гайана" }, 
	{ id: 44, name: "Гамбия" }, 
	{ id: 45, name: "Гана" }, 
	{ id: 46, name: "Гваделупа" }, 
	{ id: 47, name: "Гватемала" }, 
	{ id: 49, name: "Гвинея" }, 
	{ id: 50, name: "Гвинея-Бисау" }, 
	{ id: 51, name: "Германия" }, 
	{ id: 52, name: "Гибралтар" }, 
	{ id: 53, name: "Гондурас" }, 
	{ id: 54, name: "Гренада" }, 
	{ id: 55, name: "Гренландия" }, 
	{ id: 56, name: "Греция" }, 
	{ id: 57, name: "Грузия" }, 
	{ id: 435, name: "Гуам" }, 
	{ id: 58, name: "Дания" }, 
	{ id: 59, name: "Джибути" }, 
	{ id: 60, name: "Доминика" }, 
	{ id: 61, name: "Доминиканская республика" }, 
	{ id: 62, name: "Египет" }, 
	{ id: 63, name: "Замбия" }, 
	{ id: 64, name: "Западная Сахара" }, 
	{ id: 65, name: "Зимбабве" }, 
	{ id: 66, name: "Израиль" }, 
	{ id: 67, name: "Индия" }, 
	{ id: 68, name: "Индонезия" }, 
	{ id: 69, name: "Иордания" }, 
	{ id: 70, name: "Ирак" }, 
	{ id: 71, name: "Иран" }, 
	{ id: 72, name: "Ирландия" }, 
	{ id: 73, name: "Исландия" }, 
	{ id: 74, name: "Испания" }, 
	{ id: 75, name: "Италия" }, 
	{ id: 76, name: "Йемен" }, 
	{ id: 77, name: "Кабо-Верде" }, 
	{ id: 78, name: "Казахстан" }, 
	{ id: 79, name: "Каймановы острова" }, 
	{ id: 80, name: "Камбоджа" }, 
	{ id: 81, name: "Камерун" }, 
	{ id: 82, name: "Канада" }, 
	{ id: 83, name: "Катар" }, 
	{ id: 84, name: "Кения" }, 
	{ id: 85, name: "Кипр" }, 
	{ id: 98, name: "Киргизия" }, 
	{ id: 86, name: "Кирибати" }, 
	{ id: 87, name: "Китай" }, 
	{ id: 88, name: "КНДР" }, 
	{ id: 89, name: "Колумбия" }, 
	{ id: 90, name: "Коморские острова" }, 
	{ id: 91, name: "Конго Демократическая Республика" }, 
	{ id: 92, name: "Конго Республика" }, 
	{ id: 93, name: "Коста-Рика" }, 
	{ id: 94, name: "Кот-д'Ивуар" }, 
	{ id: 95, name: "Куба" }, 
	{ id: 96, name: "Кувейт" }, 
	{ id: 97, name: "Кука острова" }, 
	{ id: 99, name: "Лаос" }, 
	{ id: 100, name: "Латвия" }, 
	{ id: 101, name: "Лесото" }, 
	{ id: 102, name: "Либерия" }, 
	{ id: 103, name: "Ливан" }, 
	{ id: 104, name: "Ливия" }, 
	{ id: 105, name: "Литва" }, 
	{ id: 106, name: "Лихтенштейн" }, 
	{ id: 107, name: "Люксембург" }, 
	{ id: 108, name: "Маврикий" }, 
	{ id: 109, name: "Мавритания" }, 
	{ id: 110, name: "Мадагаскар" }, 
	{ id: 434, name: "Майотта" }, 
	{ id: 111, name: "Македония" }, 
	{ id: 112, name: "Малави" }, 
	{ id: 113, name: "Малайзия" }, 
	{ id: 114, name: "Мали" }, 
	{ id: 133, name: "Малые Антильские острова (Нид.)" }, 
	{ id: 115, name: "Мальдивы" }, 
	{ id: 116, name: "Мальта" }, 
	{ id: 117, name: "Марокко" }, 
	{ id: 118, name: "Мартиника" }, 
	{ id: 119, name: "Маршалловы острова" }, 
	{ id: 120, name: "Мексика" }, 
	{ id: 121, name: "Микронезия" }, 
	{ id: 122, name: "Мозамбик" }, 
	{ id: 123, name: "Молдова" }, 
	{ id: 124, name: "Монако" }, 
	{ id: 125, name: "Монголия" }, 
	{ id: 138, name: "Монтсеррат остров" }, 
	{ id: 126, name: "Мьянма" }, 
	{ id: 127, name: "Намибия" }, 
	{ id: 128, name: "Науру" }, 
	{ id: 129, name: "Непал" }, 
	{ id: 130, name: "Нигер" }, 
	{ id: 131, name: "Нигерия" }, 
	{ id: 132, name: "Нидерланды" }, 
	{ id: 134, name: "Никарагуа" }, 
	{ id: 135, name: "Новая Зеландия" }, 
	{ id: 136, name: "Новая Каледония" }, 
	{ id: 137, name: "Норвегия" }, 
	{ id: 142, name: "Объединенные Арабские Эмираты" }, 
	{ id: 144, name: "Оман" }, 
	{ id: 145, name: "Пакистан" }, 
	{ id: 146, name: "Палау" }, 
	{ id: 147, name: "Палестинские территории" }, 
	{ id: 148, name: "Панама" }, 
	{ id: 149, name: "Папуа-Новая Гвинея" }, 
	{ id: 150, name: "Парагвай" }, 
	{ id: 151, name: "Перу" }, 
	{ id: 139, name: "Питкэрн острова (Брит.)" }, 
	{ id: 152, name: "Польша" }, 
	{ id: 153, name: "Португалия" }, 
	{ id: 154, name: "Пуэрто Рико" }, 
	{ id: 155, name: "Реюньон остров" }, 
	{ id: 156, name: "Россия" }, 
	{ id: 157, name: "Руанда" }, 
	{ id: 158, name: "Румыния" }, 
	{ id: 159, name: "Сальвадор" }, 
	{ id: 6, name: "Самоа, Американское" }, 
	{ id: 160, name: "Самоа, Независимое Государство" }, 
	{ id: 161, name: "Сан-Марино" }, 
	{ id: 162, name: "Сан-Томе и Принсипи" }, 
	{ id: 163, name: "Саудовская Аравия" }, 
	{ id: 164, name: "Свазиленд" }, 
	{ id: 140, name: "Святой Елены остров" }, 
	{ id: 436, name: "Северные Марианские острова" }, 
	{ id: 165, name: "Северный Полюс" }, 
	{ id: 166, name: "Сейшелы" }, 
	{ id: 141, name: "Сен-Мартен остров (Нид.)" }, 
	{ id: 377, name: "Сен-Мартен остров (Фр.)" }, 
	{ id: 168, name: "Сен-Пьер и Микелон острова (Фр.)" }, 
	{ id: 167, name: "Сенегал" }, 
	{ id: 169, name: "Сент-Винсент и Гренадины" }, 
	{ id: 170, name: "Сент-Китс и Невис" }, 
	{ id: 171, name: "Сент-Люсия" }, 
	{ id: 172, name: "Сербия" }, 
	{ id: 173, name: "Сингапур" }, 
	{ id: 174, name: "Сирия" }, 
	{ id: 175, name: "Словакия" }, 
	{ id: 176, name: "Словения" }, 
	{ id: 177, name: "Соломоновы острова" }, 
	{ id: 178, name: "Сомали" }, 
	{ id: 179, name: "Судан" }, 
	{ id: 180, name: "Суринам" }, 
	{ id: 181, name: "США" }, 
	{ id: 182, name: "Сьерра-Леоне" }, 
	{ id: 183, name: "Таджикистан" }, 
	{ id: 186, name: "Таиланд" }, 
	{ id: 185, name: "Тайвань остров (Китай)" }, 
	{ id: 187, name: "Танзания" }, 
	{ id: 188, name: "Тёркс и Кайкос" }, 
	{ id: 189, name: "Того" }, 
	{ id: 190, name: "Тонга" }, 
	{ id: 191, name: "Тринидад и Тобаго" }, 
	{ id: 192, name: "Тувалу" }, 
	{ id: 193, name: "Тунис" }, 
	{ id: 194, name: "Туркменистан" }, 
	{ id: 195, name: "Турция" }, 
	{ id: 196, name: "Уганда" }, 
	{ id: 197, name: "Узбекистан" }, 
	{ id: 198, name: "Украина" }, 
	{ id: 199, name: "Уоллис и Футуна острова" }, 
	{ id: 200, name: "Уругвай" }, 
	{ id: 143, name: "Фарерские острова" }, 
	{ id: 201, name: "Фиджи о-в" }, 
	{ id: 202, name: "Филиппины" }, 
	{ id: 203, name: "Финляндия" }, 
	{ id: 204, name: "Фолклендские (Мальвинские) острова" }, 
	{ id: 205, name: "Франция" }, 
	{ id: 48, name: "Французская Гвиана" }, 
	{ id: 184, name: "Французская Полинезия" }, 
	{ id: 206, name: "Хорватия" }, 
	{ id: 207, name: "Центрально-Африканская Республика" }, 
	{ id: 208, name: "Чад" }, 
	{ id: 223, name: "Черногория" }, 
	{ id: 209, name: "Чехия" }, 
	{ id: 210, name: "Чили" }, 
	{ id: 211, name: "Швейцария" }, 
	{ id: 212, name: "Швеция" }, 
	{ id: 213, name: "Шри-Ланка" }, 
	{ id: 214, name: "Эквадор" }, 
	{ id: 215, name: "Экваториальная Гвинея" }, 
	{ id: 216, name: "Эритрея" }, 
	{ id: 217, name: "Эстония" }, 
	{ id: 218, name: "Эфиопия" }, 
	{ id: 219, name: "ЮАР" }, 
	{ id: 220, name: "Южная Корея" }, 
	{ id: 376, name: "Южная Осетия" }, 
	{ id: 221, name: "Ямайка" }, 
	{ id: 222, name: "Япония" } ],
	ua: [	{ id: 0, name: "Всі країни" },
	{id: 62, name: "Єгипет"},
	{id: 76, name: "Ємен"},
	{id: 73, name: "Іcландія"},
	{id: 66, name: "Ізраїль"},
	{id: 67, name: "Індія"},
	{id: 68, name: "Індонезія"},
	{id: 70, name: "Ірак"},
	{id: 71, name: "Іран"},
	{id: 72, name: "Ірландія"},
	{id: 74, name: "Іспанія"},
	{id: 75, name: "Італія"},
	{id: 375, name: "Абхазія"},
	{id: 2, name: "Австрія"},
	{id: 1, name: "Австралія"},
	{id: 3, name: "Азербайджан"},
	{id: 4, name: "Албанія"},
	{id: 5, name: "Алжир"},
	{id: 7, name: "Ангілья"},
	{id: 8, name: "Ангола"},
	{id: 9, name: "Андорра"},
	{id: 10, name: "Антігуа і Барбуда"},
	{id: 11, name: "Аргентина"},
	{id: 13, name: "Аруба"},
	{id: 14, name: "Афганістан"},
	{id: 19, name: "Білорусь"},
	{id: 15, name: "Багамські о-ви"},
	{id: 16, name: "Бангладеш"},
	{id: 17, name: "Барбадос"},
	{id: 18, name: "Бахрейн"},
	{id: 20, name: "Беліз"},
	{id: 21, name: "Бельгія"},
	{id: 22, name: "Бенін"},
	{id: 23, name: "Бермудські о-ви"},
	{id: 25, name: "Болівія"},
	{id: 24, name: "Болгарія"},
	{id: 26, name: "Боснія і Герцеґовина"},
	{id: 27, name: "Ботсвана"},
	{id: 28, name: "Бразилія"},
	{id: 29, name: "Британські Віргінські о-ви"},
	{id: 30, name: "Бруней"},
	{id: 31, name: "Буркіна-Фасо"},
	{id: 32, name: "Бурунді"},
	{id: 33, name: "Бутан"},
	{id: 38, name: "Віргінські о-ви (США)"},
	{id: 12, name: "Вірменія"},
	{id: 34, name: "Вануату"},
	{id: 224, name: "Ватикан"},
	{id: 35, name: "Велика Британія"},
	{id: 37, name: "Венесуела"},
	{id: 437, name: "Вознесения о-в"},
	{id: 199, name: "Волліс і Футуна о-ви"},
	{id: 40, name: "Вьєтнам"},
	{id: 52, name: "Гібралтар"},
	{id: 42, name: "Гаїті"},
	{id: 41, name: "Габон"},
	{id: 44, name: "Гамбія"},
	{id: 45, name: "Гана"},
	{id: 48, name: "Гвіана (Франція)"},
	{id: 49, name: "Гвінея"},
	{id: 50, name: "Гвінея-Бісау"},
	{id: 46, name: "Гваделупа"},
	{id: 47, name: "Гватемала"},
	{id: 53, name: "Гондурас"},
	{id: 54, name: "Гренада"},
	{id: 55, name: "Гренландія"},
	{id: 56, name: "Греція"},
	{id: 57, name: "Грузія"},
	{id: 58, name: "Данія"},
	{id: 59, name: "Джибуті"},
	{id: 60, name: "Домiнiка"},
	{id: 61, name: "Домініканська республіка"},
	{id: 214, name: "Еквадор"},
	{id: 215, name: "Екваторіальна Гвінея"},
	{id: 216, name: "Еритрея"},
	{id: 217, name: "Естонія"},
	{id: 218, name: "Ефіопія"},
	{id: 65, name: "Зімбабве"},
	{id: 63, name: "Замбія"},
	{id: 64, name: "Західна Сахара"},
	{id: 69, name: "Йорданія"},
	{id: 85, name: "Кіпр"},
	{id: 86, name: "Кірібаті"},
	{id: 77, name: "Кабо-Верде"},
	{id: 78, name: "Казахстан"},
	{id: 79, name: "Кайманові о-ви"},
	{id: 80, name: "Камбоджа"},
	{id: 81, name: "Камерун"},
	{id: 82, name: "Канада"},
	{id: 83, name: "Катар"},
	{id: 84, name: "Кенія"},
	{id: 98, name: "Киргизстан"},
	{id: 87, name: "Китай"},
	{id: 89, name: "Колумбія"},
	{id: 90, name: "Коморські о-ви"},
	{id: 91, name: "Конго Демократична Республіка"},
	{id: 92, name: "Конго Республіка"},
	{id: 93, name: "Коста-Ріка"},
	{id: 94, name: "Кот-д'Івуар"},
	{id: 95, name: "Куба"},
	{id: 96, name: "Кувейт"},
	{id: 97, name: "Кука о-ви"},
	{id: 102, name: "Ліберія"},
	{id: 104, name: "Лівія"},
	{id: 103, name: "Ліван"},
	{id: 106, name: "Ліхтенштейн"},
	{id: 99, name: "Лаос"},
	{id: 100, name: "Латвія"},
	{id: 101, name: "Лесото"},
	{id: 105, name: "Литва"},
	{id: 107, name: "Люксембург"},
	{id: 121, name: "Мікронезія"},
	{id: 108, name: "Маврикій"},
	{id: 109, name: "Мавританія"},
	{id: 110, name: "Мадагаскар"},
	{id: 111, name: "Македонія"},
	{id: 114, name: "Малі"},
	{id: 133, name: "Малі Антильські о-ви (Нід.)"},
	{id: 112, name: "Малаві"},
	{id: 113, name: "Малайзія"},
	{id: 115, name: "Мальдіви"},
	{id: 116, name: "Мальта"},
	{id: 117, name: "Марокко"},
	{id: 118, name: "Мартініка"},
	{id: 119, name: "Маршаллові о-ви"},
	{id: 120, name: "Мексика"},
	{id: 122, name: "Мозамбік"},
	{id: 123, name: "Молдова"},
	{id: 124, name: "Монако"},
	{id: 125, name: "Монголія"},
	{id: 138, name: "Монтсеррат о-в"},
	{id: 126, name: "Мьянма"},
	{id: 130, name: "Нігер"},
	{id: 131, name: "Нігерія"},
	{id: 132, name: "Нідерланди"},
	{id: 134, name: "Нікарагуа"},
	{id: 51, name: "Німеччина"},
	{id: 127, name: "Намібія"},
	{id: 128, name: "Науру"},
	{id: 129, name: "Непал"},
	{id: 135, name: "Нова Зеландія"},
	{id: 136, name: "Нова Каледонiя"},
	{id: 137, name: "Норвегія"},
	{id: 142, name: "Об'єднані Арабські Емірати"},
	{id: 144, name: "Оман"},
	{id: 220, name: "Південна Корея"},
	{id: 376, name: "Південна Осетія"},
	{id: 219, name: "Південно-Африканська Республіка"},
	{id: 88, name: "Північна Корея"},
	{id: 165, name: "Північний Полюс"},
	{id: 139, name: "Піткерн о-ви (Брит.)"},
	{id: 145, name: "Пакістан"},
	{id: 146, name: "Палау"},
	{id: 147, name: "Палестинські території"},
	{id: 148, name: "Панама"},
	{id: 149, name: "Папуа-Нова Гвінея"},
	{id: 150, name: "Парагвай"},
	{id: 151, name: "Перу"},
	{id: 152, name: "Польща"},
	{id: 153, name: "Португалія"},
	{id: 154, name: "Пуерто-Ріко"},
	{id: 155, name: "Реюньйон о-в"},
	{id: 156, name: "Росія"},
	{id: 157, name: "Руанда"},
	{id: 158, name: "Румунія"},
	{id: 173, name: "Сінгапур"},
	{id: 159, name: "Сальвадор"},
	{id: 6, name: "Самоа, Американське"},
	{id: 160, name: "Самоа, Незалежна Держава"},
	{id: 161, name: "Сан-Маріно"},
	{id: 162, name: "Сан-Томе і Прінсіпі"},
	{id: 163, name: "Саудівська Аравія"},
	{id: 164, name: "Свазіленд"},
	{id: 140, name: "Святої Єлени о-в"},
	{id: 436, name: "Северные Марианские острова"},
	{id: 166, name: "Сейшели"},
	{id: 141, name: "Сен-Мартен о-в (Нід.)"},
	{id: 377, name: "Сен-Мартен о-в (Фр.)"},
	{id: 168, name: "Сен-Пьєр і Мікелон о-ви (Фр.)"},
	{id: 167, name: "Сенегал"},
	{id: 169, name: "Сент-Вінсент і Гренадини"},
	{id: 170, name: "Сент-Кітс і Невіс"},
	{id: 171, name: "Сент-Люсія"},
	{id: 172, name: "Сербія"},
	{id: 174, name: "Сирія"},
	{id: 175, name: "Словаччина"},
	{id: 176, name: "Словенія"},
	{id: 177, name: "Соломонові Острови"},
	{id: 178, name: "Сомалі"},
	{id: 179, name: "Судан"},
	{id: 180, name: "Сурінам"},
	{id: 39, name: "Східний Тимор"},
	{id: 181, name: "США"},
	{id: 182, name: "Сьєрра-Леоне"},
	{id: 186, name: "Таїланд"},
	{id: 183, name: "Таджикистан"},
	{id: 185, name: "Тайвань о-в (Китай)"},
	{id: 187, name: "Танзанія"},
	{id: 188, name: "Теркс і Кайкос"},
	{id: 189, name: "Того"},
	{id: 190, name: "Тонга"},
	{id: 191, name: "Тринідад і Тобаго"},
	{id: 192, name: "Тувалу"},
	{id: 193, name: "Туніс"},
	{id: 195, name: "Туреччина"},
	{id: 194, name: "Туркменістан"},
	{id: 196, name: "Уганда"},
	{id: 36, name: "Угорщина"},
	{id: 197, name: "Узбекистан"},
	{id: 198, name: "Україна"},
	{id: 200, name: "Уругвай"},
	{id: 201, name: "Фіджі о-в"},
	{id: 202, name: "Філіппіни"},
	{id: 203, name: "Фінляндія"},
	{id: 143, name: "Фарерські острови"},
	{id: 204, name: "Фолклендські (Мальвінські) о-ви"},
	{id: 205, name: "Франція"},
	{id: 184, name: "Французька Полінезія"},
	{id: 206, name: "Хорватія"},
	{id: 207, name: "Центрально-Африканська Республіка"},
	{id: 210, name: "Чілі"},
	{id: 208, name: "Чад"},
	{id: 209, name: "Чехія"},
	{id: 223, name: "Чорногорія"},
	{id: 211, name: "Швейцарія"},
	{id: 212, name: "Швеція"},
	{id: 213, name: "Шрі-Ланка"},
	{id: 221, name: "Ямайка"},
	{id: 222, name: "Японія"},
	{id: 43, name: "Ґаяна"}],
	lt:[	{ id: 0, name: "Visos šalys" },
	{ id: 375, name: "Abchazija"}, 
	{ id: 14, name: "Afganistanas"}, 
	{ id: 72, name: "Airija"}, 
	{ id: 4, name: "Albanija"}, 
	{ id: 5, name: "Alžyras"}, 
	{ id: 9, name: "Andora"}, 
	{ id: 7, name: "Anglija"}, 
	{ id: 8, name: "Angola"}, 
	{ id: 10, name: "Antigva ir Barbuda"}, 
	{ id: 133, name: "Antilų Salos"}, 
	{ id: 11, name: "Argentina"}, 
	{ id: 12, name: "Armėnija"}, 
	{ id: 13, name: "Aruba"}, 
	{ id: 1, name: "Australija"}, 
	{ id: 2, name: "Austrija"}, 
	{ id: 3, name: "Azerbaidžanas"}, 
	{ id: 15, name: "Bahamos"}, 
	{ id: 18, name: "Bahreinas"}, 
	{ id: 19, name: "Baltarusija"}, 
	{ id: 16, name: "Bangladešas"}, 
	{ id: 17, name: "Barbadosas"}, 
	{ id: 21, name: "Belgija"}, 
	{ id: 20, name: "Belizas"}, 
	{ id: 22, name: "Beninas"}, 
	{ id: 23, name: "Bermudų salos"}, 
	{ id: 50, name: "Bisau Gvinėja"}, 
	{ id: 25, name: "Bolivija"}, 
	{ id: 26, name: "Bosnija ir Hercegovina"}, 
	{ id: 27, name: "Botsvana"}, 
	{ id: 28, name: "Brazilija"}, 
	{ id: 30, name: "Brunėjus"}, 
	{ id: 24, name: "Bulgarija"}, 
	{ id: 31, name: "Burkina Fasas"}, 
	{ id: 32, name: "Burundis"}, 
	{ id: 33, name: "Butanas"}, 
	{ id: 208, name: "Čadas"}, 
	{ id: 209, name: "Čekija"}, 
	{ id: 207, name: "Centrinės Afrikos Respublika"}, 
	{ id: 210, name: "Čilė"}, 
	{ id: 58, name: "Danija"}, 
	{ id: 35, name: "Didžioji Britanija"}, 
	{ id: 60, name: "Dominika"}, 
	{ id: 61, name: "Dominikos Respublika"}, 
	{ id: 94, name: "Dramblio Kaulo Krantas"}, 
	{ id: 59, name: "Džibutis"}, 
	{ id: 62, name: "Egiptas"}, 
	{ id: 214, name: "Ekvadoras"}, 
	{ id: 215, name: "Ekvatoriaus Gvinėja"}, 
	{ id: 140, name: "Elenos Sala"}, 
	{ id: 216, name: "Eritrėja"}, 
	{ id: 217, name: "Estija"}, 
	{ id: 218, name: "Etiopija"}, 
	{ id: 143, name: "Farerų Salos"}, 
	{ id: 201, name: "Fidžis"}, 
	{ id: 202, name: "Filipinai"}, 
	{ id: 204, name: "Folklando (Malvinų) Salos"}, 
	{ id: 41, name: "Gabonas"}, 
	{ id: 43, name: "Gajana"}, 
	{ id: 44, name: "Gambija"}, 
	{ id: 45, name: "Gana"}, 
	{ id: 52, name: "Gibraltaras"}, 
	{ id: 56, name: "Graikija"}, 
	{ id: 54, name: "Grenada"}, 
	{ id: 55, name: "Grenlandija"}, 
	{ id: 57, name: "Gruzija"}, 
	{ id: 46, name: "Gvadelupa"}, 
	{ id: 47, name: "Gvatemala"}, 
	{ id: 48, name: "Gviana"}, 
	{ id: 49, name: "Gvinėja"}, 
	{ id: 42, name: "Haitis"}, 
	{ id: 53, name: "Hondūras"}, 
	{ id: 67, name: "Indija"}, 
	{ id: 68, name: "Indonezija"}, 
	{ id: 70, name: "Irakas"}, 
	{ id: 71, name: "Iranas"}, 
	{ id: 73, name: "Islandija"}, 
	{ id: 74, name: "Ispanija"}, 
	{ id: 75, name: "Italija"}, 
	{ id: 66, name: "Izraelis"}, 
	{ id: 221, name: "Jamaika"}, 
	{ id: 222, name: "Japonija"}, 
	{ id: 76, name: "Jemenas"}, 
	{ id: 69, name: "Jordanija"}, 
	{ id: 181, name: "Jungtinės Amerikos Valstijos"}, 
	{ id: 142, name: "Jungtiniai Arabų Emyratai"}, 
	{ id: 223, name: "Juodkalnija"}, 
	{ id: 79, name: "Kaimanų Salos"}, 
	{ id: 80, name: "Kambodža"}, 
	{ id: 81, name: "Kamerūnas"}, 
	{ id: 82, name: "Kanada"}, 
	{ id: 83, name: "Kataras"}, 
	{ id: 78, name: "Kazachija"}, 
	{ id: 84, name: "Kenija"}, 
	{ id: 87, name: "Kinija"}, 
	{ id: 85, name: "Kipras"}, 
	{ id: 98, name: "Kirgizija"}, 
	{ id: 86, name: "Kiribatis"}, 
	{ id: 89, name: "Kolumbija"}, 
	{ id: 90, name: "Komorai"}, 
	{ id: 91, name: "Kongo Demokratinė Respublika"}, 
	{ id: 92, name: "Kongo Respublika"}, 
	{ id: 93, name: "Kosta Rika"}, 
	{ id: 206, name: "Kroatija"}, 
	{ id: 95, name: "Kuba"}, 
	{ id: 97, name: "Kuko Salos"}, 
	{ id: 96, name: "Kuveitas"}, 
	{ id: 99, name: "Laosas"}, 
	{ id: 100, name: "Latvija"}, 
	{ id: 152, name: "Lenkija"}, 
	{ id: 101, name: "Lesotas"}, 
	{ id: 103, name: "Libanas"}, 
	{ id: 102, name: "Liberija"}, 
	{ id: 104, name: "Libija"}, 
	{ id: 106, name: "Lichtenšteinas"}, 
	{ id: 105, name: "Lietuva"}, 
	{ id: 107, name: "Liuksemburgas"}, 
	{ id: 110, name: "Madagaskaras"}, 
	{ id: 111, name: "Makedonija"}, 
	{ id: 113, name: "Malaizija"}, 
	{ id: 112, name: "Malavis"}, 
	{ id: 115, name: "Maldyvai"}, 
	{ id: 114, name: "Malis"}, 
	{ id: 116, name: "Malta"}, 
	{ id: 117, name: "Marokas"}, 
	{ id: 119, name: "Maršalo Salos"}, 
	{ id: 118, name: "Martinika"}, 
	{ id: 108, name: "Mauricijus"}, 
	{ id: 109, name: "Mauritanija"}, 
	{ id: 120, name: "Meksika"}, 
	{ id: 29, name: "Mergelių Salos (Didžioji Britanija)"}, 
	{ id: 126, name: "Mianmaras"}, 
	{ id: 121, name: "Mikronezija"}, 
	{ id: 123, name: "Moldavija"}, 
	{ id: 124, name: "Monakas"}, 
	{ id: 125, name: "Mongolija"}, 
	{ id: 138, name: "Montserato Sala"}, 
	{ id: 122, name: "Mozambikas"}, 
	{ id: 127, name: "Namibija"}, 
	{ id: 136, name: "Naujoji Kaledonija"}, 
	{ id: 135, name: "Naujoji Zelandija"}, 
	{ id: 128, name: "Nauru"}, 
	{ id: 129, name: "Nepalas"}, 
	{ id: 131, name: "Nigerija"}, 
	{ id: 130, name: "Nigeris"}, 
	{ id: 134, name: "Nikaragva"}, 
	{ id: 436, name: "Northern Mariam Islands"}, 
	{ id: 137, name: "Norvegija"}, 
	{ id: 132, name: "Olandija"}, 
	{ id: 144, name: "Omanas"}, 
	{ id: 145, name: "Pakistanas"}, 
	{ id: 146, name: "Palau"}, 
	{ id: 147, name: "Palestina"}, 
	{ id: 148, name: "Panama"}, 
	{ id: 149, name: "Papua ir Naujoji Gvinėja"}, 
	{ id: 150, name: "Paragvajus"}, 
	{ id: 151, name: "Peru"}, 
	{ id: 219, name: "Pietų Afrikos Respublika"}, 
	{ id: 220, name: "Pietų Korėja"}, 
	{ id: 376, name: "Pietų Osetija"}, 
	{ id: 139, name: "Pitkerno Salos"}, 
	{ id: 153, name: "Portugalija"}, 
	{ id: 205, name: "Prancūzija"}, 
	{ id: 184, name: "Prancūzijos Polinezija"}, 
	{ id: 154, name: "Puerto Rikas"}, 
	{ id: 155, name: "Rejunjono Sala"}, 
	{ id: 157, name: "Ruanda"}, 
	{ id: 158, name: "Rumunija"}, 
	{ id: 156, name: "Rusija"}, 
	{ id: 6, name: "Rytų Samoa"}, 
	{ id: 39, name: "Rytų Timoras"}, 
	{ id: 177, name: "Saliamono Salos"}, 
	{ id: 159, name: "Salvadoras"}, 
	{ id: 160, name: "Samoa"}, 
	{ id: 161, name: "San Marinas"}, 
	{ id: 377, name: "San Marteno Salos (Prancūzija)"}, 
	{ id: 162, name: "San Tomė ir Prinsipė"}, 
	{ id: 163, name: "Saudo Arabija"}, 
	{ id: 166, name: "Seišeliai"}, 
	{ id: 168, name: "Sen Pjeras ir Mikelono Salos"}, 
	{ id: 167, name: "Senegalas"}, 
	{ id: 170, name: "Sent Kristoferis ir Nevis"}, 
	{ id: 171, name: "Sent Lusija"}, 
	{ id: 169, name: "Sent Vinsentas ir Grenadinai"}, 
	{ id: 172, name: "Serbija"}, 
	{ id: 165, name: "Šiaurės Ašigalis"}, 
	{ id: 88, name: "Šiaurės Korėja"}, 
	{ id: 182, name: "Siera Leonė"}, 
	{ id: 141, name: "Sin Marteno Salos (Nyderlandai)"}, 
	{ id: 173, name: "Singapūras"}, 
	{ id: 174, name: "Sirija"}, 
	{ id: 175, name: "Slovakija"}, 
	{ id: 176, name: "Slovėnija"}, 
	{ id: 178, name: "Somalis"}, 
	{ id: 213, name: "Šri Lanka"}, 
	{ id: 179, name: "Sudanas"}, 
	{ id: 203, name: "Suomija"}, 
	{ id: 180, name: "Surinamas"}, 
	{ id: 164, name: "Svazilandas"}, 
	{ id: 212, name: "Švedija"}, 
	{ id: 211, name: "Šveicarija"}, 
	{ id: 183, name: "Tadžikija"}, 
	{ id: 186, name: "Tailandas"}, 
	{ id: 185, name: "Taivanas"}, 
	{ id: 187, name: "Tanzanija"}, 
	{ id: 188, name: "Terksaso ir Kaikoso Salos"}, 
	{ id: 189, name: "Togas"}, 
	{ id: 190, name: "Tonga"}, 
	{ id: 191, name: "Trinidadas ir Tobagas"}, 
	{ id: 193, name: "Tunisas"}, 
	{ id: 195, name: "Turkija"}, 
	{ id: 194, name: "Turkmėnija"}, 
	{ id: 192, name: "Tuvalu"}, 
	{ id: 196, name: "Uganda"}, 
	{ id: 198, name: "Ukraina"}, 
	{ id: 200, name: "Urugvajus"}, 
	{ id: 197, name: "Uzbekija"}, 
	{ id: 64, name: "Vakarų Sachara"}, 
	{ id: 34, name: "Vanuatu"}, 
	{ id: 224, name: "Vatikanas"}, 
	{ id: 37, name: "Venesuela"}, 
	{ id: 36, name: "Vengrija"}, 
	{ id: 40, name: "Vietnamas"}, 
	{ id: 38, name: "Virdžinijos Salos (JAV)"}, 
	{ id: 51, name: "Vokietija"}, 
	{ id: 199, name: "Volisas ir Futūna"}, 
	{ id: 77, name: "Žaliojo Kyšulio Salos"}, 
	{ id: 63, name: "Zambija"}, 
	{ id: 65, name: "Zimbabvė"}, 
	{ id: 437, name: "Вознесения о-в"}],
	en:[	{ id: 0, name: "All countries" },
	{ id: 375, name: "Abkhazia"}, 
	{ id: 14, name: "Afghanistan"}, 
	{ id: 4, name: "Albania"}, 
	{ id: 5, name: "Algeria"}, 
	{ id: 9, name: "Andorra"}, 
	{ id: 8, name: "Angola"}, 
	{ id: 7, name: "Anguilla"}, 
	{ id: 10, name: "Antigua and Barbuda"}, 
	{ id: 11, name: "Argentina"}, 
	{ id: 12, name: "Armenia"}, 
	{ id: 13, name: "Aruba"}, 
	{ id: 437, name: "Ascension Island"}, 
	{ id: 1, name: "Australia"}, 
	{ id: 2, name: "Austria"}, 
	{ id: 3, name: "Azerbaijan"}, 
	{ id: 15, name: "Bahamas"}, 
	{ id: 18, name: "Bahrain"}, 
	{ id: 16, name: "Bangladesh"}, 
	{ id: 17, name: "Barbados"}, 
	{ id: 19, name: "Belarus"}, 
	{ id: 21, name: "Belgium"}, 
	{ id: 20, name: "Belize"}, 
	{ id: 22, name: "Benin"}, 
	{ id: 23, name: "Bermuda"}, 
	{ id: 33, name: "Bhutan"}, 
	{ id: 25, name: "Bolivia"}, 
	{ id: 26, name: "Bosnia and Herzegovina"}, 
	{ id: 27, name: "Botswana"}, 
	{ id: 28, name: "Brazil"}, 
	{ id: 29, name: "British Virgin Islands"}, 
	{ id: 30, name: "Brunei"}, 
	{ id: 24, name: "Bulgaria"}, 
	{ id: 31, name: "Burkina Faso"}, 
	{ id: 32, name: "Burundi"}, 
	{ id: 80, name: "Cambodia"}, 
	{ id: 81, name: "Cameroon"}, 
	{ id: 82, name: "Canada"}, 
	{ id: 77, name: "Cape Verde"}, 
	{ id: 79, name: "Cayman Islands"}, 
	{ id: 207, name: "Central African Republic"}, 
	{ id: 208, name: "Chad"}, 
	{ id: 210, name: "Chile"}, 
	{ id: 87, name: "China"}, 
	{ id: 89, name: "Colombia"}, 
	{ id: 90, name: "Comoros"}, 
	{ id: 97, name: "Cook Islands"}, 
	{ id: 93, name: "Costa Rica"}, 
	{ id: 94, name: "Cote d'Ivoire"}, 
	{ id: 206, name: "Croatia"}, 
	{ id: 95, name: "Cuba"}, 
	{ id: 85, name: "Cyprus"}, 
	{ id: 209, name: "Czech Republic"}, 
	{ id: 91, name: "Democratic Republic of The Congo"}, 
	{ id: 58, name: "Denmark"}, 
	{ id: 59, name: "Djibouti"}, 
	{ id: 60, name: "Dominica"}, 
	{ id: 61, name: "Dominican Republic"}, 
	{ id: 39, name: "East Timor"}, 
	{ id: 214, name: "Ecuador"}, 
	{ id: 62, name: "Egypt"}, 
	{ id: 159, name: "El Salvador"}, 
	{ id: 215, name: "Equatorial Guinea"}, 
	{ id: 216, name: "Eritrea"}, 
	{ id: 217, name: "Estonia"}, 
	{ id: 218, name: "Ethiopia"}, 
	{ id: 204, name: "Falkland Islands"}, 
	{ id: 143, name: "Faroe Islands"}, 
	{ id: 201, name: "Fiji"}, 
	{ id: 203, name: "Finland"}, 
	{ id: 205, name: "France"}, 
	{ id: 48, name: "French Guiana"}, 
	{ id: 184, name: "French Polynesia"}, 
	{ id: 41, name: "Gabon"}, 
	{ id: 44, name: "Gambia"}, 
	{ id: 57, name: "Georgia"}, 
	{ id: 51, name: "Germany"}, 
	{ id: 45, name: "Ghana"}, 
	{ id: 52, name: "Gibraltar"}, 
	{ id: 56, name: "Greece"}, 
	{ id: 55, name: "Greenland"}, 
	{ id: 54, name: "Grenada"}, 
	{ id: 46, name: "Guadeloupe"}, 
	{ id: 435, name: "Guam"}, 
	{ id: 47, name: "Guatemala"}, 
	{ id: 49, name: "Guinea"}, 
	{ id: 50, name: "Guinea-Bissau"}, 
	{ id: 43, name: "Guyana"}, 
	{ id: 42, name: "Haiti"}, 
	{ id: 53, name: "Honduras"}, 
	{ id: 36, name: "Hungary"}, 
	{ id: 73, name: "Iceland"}, 
	{ id: 67, name: "India"}, 
	{ id: 68, name: "Indonesia"}, 
	{ id: 71, name: "Iran"}, 
	{ id: 70, name: "Iraq"}, 
	{ id: 72, name: "Ireland"}, 
	{ id: 66, name: "Israel"}, 
	{ id: 75, name: "Italy"}, 
	{ id: 221, name: "Jamaica"}, 
	{ id: 222, name: "Japan"}, 
	{ id: 69, name: "Jordan"}, 
	{ id: 78, name: "Kazakhstan"}, 
	{ id: 84, name: "Kenya"}, 
	{ id: 98, name: "Kirghizstan"}, 
	{ id: 86, name: "Kiribati"}, 
	{ id: 96, name: "Kuwait"}, 
	{ id: 99, name: "Lao People's Democratic Republic"}, 
	{ id: 100, name: "Latvia"}, 
	{ id: 103, name: "Lebanon"}, 
	{ id: 101, name: "Lesotho"}, 
	{ id: 102, name: "Liberia"}, 
	{ id: 104, name: "Libya"}, 
	{ id: 106, name: "Liechtenstein"}, 
	{ id: 105, name: "Lithuania"}, 
	{ id: 107, name: "Luxembourg"}, 
	{ id: 111, name: "Macedonia"}, 
	{ id: 110, name: "Madagascar"}, 
	{ id: 112, name: "Malawi"}, 
	{ id: 113, name: "Malaysia"}, 
	{ id: 115, name: "Maldives"}, 
	{ id: 114, name: "Mali"}, 
	{ id: 116, name: "Malta"}, 
	{ id: 119, name: "Marshall Islands"}, 
	{ id: 118, name: "Martinique"}, 
	{ id: 109, name: "Mauritania"}, 
	{ id: 108, name: "Mauritius"}, 
	{ id: 434, name: "Mayotte"}, 
	{ id: 120, name: "Mexico"}, 
	{ id: 121, name: "Micronesia"}, 
	{ id: 123, name: "Moldova"}, 
	{ id: 124, name: "Monaco"}, 
	{ id: 125, name: "Mongolia"}, 
	{ id: 223, name: "Montenegro"}, 
	{ id: 138, name: "Montserrat"}, 
	{ id: 117, name: "Morocco"}, 
	{ id: 122, name: "Mozambique"}, 
	{ id: 126, name: "Myanmar"}, 
	{ id: 127, name: "Namibia"}, 
	{ id: 128, name: "Nauru"}, 
	{ id: 129, name: "Nepal"}, 
	{ id: 132, name: "Netherlands"}, 
	{ id: 133, name: "Netherlands Antilles"}, 
	{ id: 136, name: "New Caledonia"}, 
	{ id: 135, name: "New Zealand"}, 
	{ id: 134, name: "Nicaragua"}, 
	{ id: 130, name: "Niger"}, 
	{ id: 131, name: "Nigeria"}, 
	{ id: 88, name: "North Korea"}, 
	{ id: 165, name: "North Pole"}, 
	{ id: 436, name: "Northern Mariam Islands"}, 
	{ id: 137, name: "Norway"}, 
	{ id: 144, name: "Oman"}, 
	{ id: 145, name: "Pakistan"}, 
	{ id: 146, name: "Palau"}, 
	{ id: 147, name: "Palestinian Territory"}, 
	{ id: 148, name: "Panama"}, 
	{ id: 149, name: "Papua New Guinea"}, 
	{ id: 150, name: "Paraguay"}, 
	{ id: 151, name: "Peru"}, 
	{ id: 202, name: "Philippines"}, 
	{ id: 139, name: "Pitcairn Islands"}, 
	{ id: 152, name: "Poland"}, 
	{ id: 153, name: "Portugal"}, 
	{ id: 154, name: "Puerto Rico"}, 
	{ id: 83, name: "Qatar"}, 
	{ id: 220, name: "Republic of Korea"}, 
	{ id: 92, name: "Republic of the Congo"}, 
	{ id: 155, name: "Reunion Island"}, 
	{ id: 158, name: "Romania"}, 
	{ id: 156, name: "Russia"}, 
	{ id: 157, name: "Rwanda"}, 
	{ id: 162, name: "S. Tome and Principe"}, 
	{ id: 140, name: "Saint Helena"}, 
	{ id: 170, name: "Saint Kitts and Nevis"}, 
	{ id: 171, name: "Saint Lucia"}, 
	{ id: 377, name: "Saint Martin"}, 
	{ id: 168, name: "Saint Pierre And Miquelon"}, 
	{ id: 169, name: "Saint Vincent"}, 
	{ id: 6, name: "Samoa"}, 
	{ id: 160, name: "Samoa"}, 
	{ id: 161, name: "San Marino"}, 
	{ id: 163, name: "Saudi Arabia"}, 
	{ id: 167, name: "Senegal"}, 
	{ id: 172, name: "Serbia"}, 
	{ id: 166, name: "Seychelles"}, 
	{ id: 182, name: "Sierra Leone"}, 
	{ id: 173, name: "Singapore"}, 
	{ id: 141, name: "Sint Maarten"}, 
	{ id: 175, name: "Slovakia"}, 
	{ id: 176, name: "Slovenia"}, 
	{ id: 177, name: "Solomon Islands"}, 
	{ id: 178, name: "Somalia"}, 
	{ id: 219, name: "South Africa"}, 
	{ id: 376, name: "South Osetia"}, 
	{ id: 74, name: "Spain"}, 
	{ id: 213, name: "Sri Lanka"}, 
	{ id: 179, name: "Sudan"}, 
	{ id: 180, name: "Suriname"}, 
	{ id: 164, name: "Swaziland"}, 
	{ id: 212, name: "Sweden"}, 
	{ id: 211, name: "Switzerland"}, 
	{ id: 174, name: "Syrian Arab Republic"}, 
	{ id: 183, name: "Tadjikistan"}, 
	{ id: 185, name: "Taiwan"}, 
	{ id: 186, name: "Thailand"}, 
	{ id: 189, name: "Togo"}, 
	{ id: 190, name: "Tonga"}, 
	{ id: 191, name: "Trinidad and Tobago"}, 
	{ id: 193, name: "Tunisia"}, 
	{ id: 195, name: "Turkey"}, 
	{ id: 194, name: "Turkmenistan"}, 
	{ id: 188, name: "Turks and Caicos"}, 
	{ id: 192, name: "Tuvalu"}, 
	{ id: 196, name: "Uganda"}, 
	{ id: 198, name: "Ukraine"}, 
	{ id: 142, name: "United Arab Emirates"}, 
	{ id: 35, name: "United Kingdom of Great Britain"}, 
	{ id: 187, name: "United Republic of Tanzania"}, 
	{ id: 181, name: "United States of America"}, 
	{ id: 200, name: "Uruguay"}, 
	{ id: 38, name: "US Virgin Islands"}, 
	{ id: 197, name: "Uzbekistan"}, 
	{ id: 34, name: "Vanuatu"}, 
	{ id: 224, name: "Vatican"}, 
	{ id: 37, name: "Venezuela"}, 
	{ id: 40, name: "Vietnam"}, 
	{ id: 199, name: "Wallis And Futuna"}, 
	{ id: 64, name: "Western Sahara"}, 
	{ id: 76, name: "Yemen"}, 
	{ id: 63, name: "Zambia"}, 
	{ id: 65, name: "Zimbabwe"}] 
};